### ISSUE TITLE
Error when clicking on New > Project

### ISSUE THREAD

**Issue by LatvianModder** [DemonWav/MinecraftDev#70]
Error report: http://pastebin.com/E581ELJf
Idea version: 2016.2.4
Plugin version: alpha-0.2.12

**Comment by loordgek** [comment]
same here but i click on navigate > class

**Comment by DemonWav** [comment]
I don't know how I messed that icon refactor up so badly...sorry about that.

**Comment by DemonWav** [comment]
I have no idea how this error is happening, actually. Everything is setup find in PlatformAssets.

**Comment by sgdc3** [comment]
@DemonWav I can't create a new project at all.

**Comment by DemonWav** [comment]
I'll push out a new build and see if maybe that fixes it? Maybe something wacky happened to the resources with this build.

**Comment by DemonWav** [comment]
See if updating to alpha-0.2.13 fixes it. As far as I know I didn't change anything that would fix it, but I'm thinking alpha-0.2.12 may have just been a botched build.

**Comment by DemonWav** [comment]
Ah, I believe I may have tracked down the issue. I think it's a case-sensitivity issue. The icon was previously `mixin_dark.png`, but I changed it to `Mixin_dark.png` to match the naming convention of the rest of the icons. I think because the names are only different in case, the new file isn't being set right (or it's being copied, but the name stays the same without changing case). This later causes it to fail finding the icon because there isn't a `Mixin_dark.png` file available. I'll revert that name change and see if that fixes the issue.
